# Automatically generated by configure - do not modify

all:
SRC_PATH=/workdir
TARGET_DIRS=x86_64-linux-user x86_64-softmmu
GDB=/usr/bin/gdb
SUBDIRS= contrib/plugins
PYTHON=/workdir/run/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/workdir/run/pyvenv/bin/python3 -B /workdir/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/workdir/run/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-linux-user x86_64-softmmu
